#version: "3"
services:
  hub:
    image: selenium/hub
    ports:
      - "4444:4444"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U example"]
      interval: 20s
      timeout: 10s
      retries: 10
  chrome:
    image: selenium/node-chrome
    healthcheck:
      test: [ "CMD-SHELL", "ch_isready -U example" ]
      interval: 20s
      timeout: 10s
      retries: 10
    shm_size: '1g'
    deploy:
      replicas: 1
    env_file: .env

  firefox:
    image: selenium/node-firefox
    healthcheck:
      test: [ "CMD-SHELL", "fr_isready -U example" ]
      interval: 20s
      timeout: 10s
      retries: 10
    shm_size: '1g'
    deploy:
      replicas: 1
    env_file: .env


