#version: "3"
services:
  hub:
    image: selenium/hub
    ports:
      - "4444:4444"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U example"]
      interval: 20s
      timeout: 10s
      retries: 10
  chrome:
    image: selenium/node-chrome
    shm_size: '1g'
    depends_on:
      hub:
        condition: service_healthy
    deploy:
      replicas: 1
    env_file: .env

  firefox:
    image: selenium/node-firefox
    depends_on:
      chrome:
        condition: service_healthy
    shm_size: '1g'
    deploy:
      replicas: 1
    env_file: .env


