#version: "3"
services:
  hub:
    image: selenium/hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome
    shm_size: '1g'
    depends_on:
      - hub
    deploy:
      replicas: 0
    env_file: .env

  firefox:
    image: selenium/node-firefox
    shm_size: '1g'
    depends_on:
      - hub
    deploy:
      replicas: 0
    env_file: .env


